### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by Quantum-cross** [srg320/FpgaSnes#1]
This looks like a really awesome project, a lot of people are getting interested in porting it to the DE-10 Nano for the MiSTer platform:
https://github.com/MiSTer-devel/Main_MiSTer/wiki

I see there is no license on the project, did you want to clarify how the code can be used?

**Comment by poopybunghole** [comment]
GPL v3 license added yesterday

**Comment by Quantum-cross** [comment]
Awesome! Thanks for the hard work Sergey.
